# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Governator < Formula
  desc "Governator CLI - AI-powered task orchestration tool"
  homepage "https://github.com/cmtonkinson/governator"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cmtonkinson/governator/releases/download/v1.0.0/governator_1.0.0_darwin_amd64.tar.gz"
      sha256 "b62f6fb820d415e819c4b53257189d6d6bbe092e30c03b3204e429250b71feca"

      def install
        bin.install "governator"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cmtonkinson/governator/releases/download/v1.0.0/governator_1.0.0_darwin_arm64.tar.gz"
      sha256 "e2c353465029add18e4e656c88f9fe8887b5a206382a0d6fc9a984ad5c84c483"

      def install
        bin.install "governator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cmtonkinson/governator/releases/download/v1.0.0/governator_1.0.0_linux_amd64.tar.gz"
      sha256 "59161ce83ef7ce00f95f2246e4617cb13b92ebd465bbe36775b520e24934e1b1"
      def install
        bin.install "governator"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cmtonkinson/governator/releases/download/v1.0.0/governator_1.0.0_linux_arm64.tar.gz"
      sha256 "4762f6474d9a73edb2648db82d646ca362bea12fb393b1bae6b3b9714b2e216c"
      def install
        bin.install "governator"
      end
    end
  end

  test do
    system "#{bin}/governator", "version"
  end
end
